// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vanhsuisvxvclxdgutaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbmhzdWlzdnh2Y2x4ZGd1dGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNjA4OTAsImV4cCI6MjA4NjczNjg5MH0.12dipjMKxJzZ93aGRSw3GnYYBb19E-FvdDEAGyH35Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});